ARG BASE_CONTAINER=ubuntu:focal-20210416@sha256:86ac87f73641c920fb42cc9612d4fb57b5626b56ea2a19b894d0673fd5b4f2e9

FROM $BASE_CONTAINER
LABEL maintainer "Konstantin Taletskiy <konstantin@taletskiy.com>"

ENV CUDA_VERSION 11.3.1
ENV CUDA_PKG_VERSION 11-3=$CUDA_VERSION-1
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=11.3 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450"
ENV NCCL_VERSION 2.9.9
ENV CUDNN_VERSION 8.2.0.53
ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs

RUN apt-get update && apt-get install -y --no-install-recommends \
        gnupg2 curl ca-certificates && \
    curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub | apt-key add - && \
    echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /" > /etc/apt/sources.list.d/cuda.list && \
    echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update && apt-get install -y --no-install-recommends \
        cuda-cudart-11-3=11.3.109-1 \
        cuda-compat-11-3 && \
    ln -s cuda-11.3 /usr/local/cuda && \
    echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf && \
    apt-get update && apt-get install -y --no-install-recommends \
        cuda-libraries-11-3=11.3.1-1 \
        cuda-nvtx-11-3=11.3.109-1 \
        cuda-nvml-dev-11-3=11.3.58-1 \
        cuda-minimal-build-11-3=11.3.1-1 \
        cuda-libraries-dev-11-3=11.3.1-1 \
        cuda-cudart-dev-11-3=11.3.109-1 \
        cuda-command-line-tools-11-3=11.3.1-1 \
        libnpp-11-3=11.3.3.95-1 \
        libnpp-dev-11-3=11.3.3.95-1 \
        libtinfo5 \
        libncursesw5 \
        libcublas-11-3=11.5.1.109-1 \
        libcublas-dev-11-3=11.5.1.109-1 \
        libcusparse-11-3=11.6.0.109-1 \
        libcusparse-dev-11-3=11.6.0.109-1 \
        libnccl2=$NCCL_VERSION-1+cuda11.3 \
        libnccl-dev=2.9.9-1+cuda11.3 \
        libcudnn8=$CUDNN_VERSION-1+cuda11.3 \
        libcudnn8-dev=$CUDNN_VERSION-1+cuda11.3 && \
    apt-mark hold libcublas-11-3 libnccl2 libcudnn8 && \
    apt-get purge --autoremove -y curl && \
    rm -rf /var/lib/apt/lists/*
