name: Build Notebook Docker images

# Global environment variables and secrets
env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  DOCKER_IMAGE: polusai/ubuntu-cuda
  IMAGE_TAG: jammy-20220531-cuda-11-7

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notebook-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Notebook Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_jammy-20220531-cuda-11-7
          push: true
          tags: ${{env.DOCKER_IMAGE}}:${{env.IMAGE_TAG}}
